samples:
    D-0-1: /juno/work/greenbaum/projects/TRI_EPIGENETIC/megalodon/D-0-1/per_read_modified_base_calls.txt
    D-0-2: /juno/work/greenbaum/projects/TRI_EPIGENETIC/megalodon/D-0-2/per_read_modified_base_calls.txt
    D-0-3: /juno/work/greenbaum/projects/TRI_EPIGENETIC/megalodon/D-0-3/per_read_modified_base_calls.txt
    D-A-1: /juno/work/greenbaum/projects/TRI_EPIGENETIC/megalodon/D-A-1/per_read_modified_base_calls.txt
    D-A-2: /juno/work/greenbaum/projects/TRI_EPIGENETIC/megalodon/D-A-2/per_read_modified_base_calls.txt
    D-A-3: /juno/work/greenbaum/projects/TRI_EPIGENETIC/megalodon/D-A-3/per_read_modified_base_calls.txt